apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: 7wesley/foodclient:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
#A servuce attached to a pod using its name
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  #Make it an external service
  #Assigns it an external IP address
  #Pods are always given an interal ip (cluster-ip), but load
  #balance gives an external IP
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 #service port (the port to access the service)
    targetPort: 80 #container/pod port, must match containerport
    nodePort: 30000 #external IP (30000-23767)
