version: '3'

services:
  database:
    image: postgres
    restart: always
    ports:
      - "10002:5432"
    env_file: .env

  backend:
    build: ./server
    ports:
      - "10001:10001"
    env_file: .env
    depends_on:
      - database

  frontend:
    build: ./client
    volumes:
      - $PWD/client:/usr/local/apache2/htdocs/
    ports:
      - "10000:80"
    depends_on:
      - backend