apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  serviceAccount: jenkins
  containers:
    - name: docker
      image: docker:20.10.8
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: kubectl
      image: lachlanevenson/k8s-kubectl:v1.22.1
      command:
        - cat
      tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock